server 0.pool.ntp.org iburst
server 1.pool.ntp.org iburst

allow 192.168.1.0/24        # allow the range of ip you want to sync it with ntp server .

driftfile /var/lib/chrony/drift
rtcsync
makestep 1.0 3
